version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin
      #runtime: nvidia
    user: 1000:984
    container_name: jellyfin
    group_add:
      - "989"
    network_mode: "host"
    volumes:
      - /home/harsh/jellyfin/config:/config
      - /home/harsh/jellyfin/cache:/cache
      - /mnt/media:/media
    devices:
      # VAAPI Devices
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    environment:
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: all
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]

  # Sonarr
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=984
      - TZ=Asia/Kolkata
    volumes:
      - /home/harsh/sonarr/config:/config
      - /mnt/media/library/TV-Series:/tv 
      - /mnt/media/library/raw:/downloads
      - /mnt/media/library/metadata:/metadata 
    ports:
      - 8989:8989
    restart: unless-stopped

  # Radarr
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=984
      - TZ=Asia/Kolkata
    volumes:
      - /home/harsh/radarr/config:/config
      - /mnt/media/library/Movies:/movie 
      - /mnt/media/library/raw:/downloads
      - /mnt/media/library/metadata:/metadata 
    ports:
      - 7878:7878
    restart: unless-stopped

  # Prowlarr
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=984
      - TZ=Asia/Kolkata
    volumes:
      - /home/harsh/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  # Bazarr
  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=984
      - TZ=Asia/Kolkata
    volumes:
      - /home/harsh/bazarr/config:/config
      - /mnt/media/library/TV-Series:/tv 
      - /mnt/media/library/Movies/movie 
    ports:
      - 6767:6767
    restart: unless-stopped

  # qbit torrent
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=984
      - TZ=Asia/Kolkata
      - WEBUI_PORT=8080
    volumes:
      - /home/harsh/qbit/config:/config
      - /mnt/media/library/raw:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped

  # Heimdall
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=984
      - TZ=Asia/Kolkata
    volumes:
      - /home/harsh/heim/config:/config
    ports:
      - 85:80
      - 443:443
    restart: unless-stopped
